---
:id:
  :MIMSY: SITES.SKEY
  :module: ''
  :column: ''
  :instructions: 'Not mapped'
:language:
  :MIMSY: SITES.LANGUAGE
  :module: ''
  :column: ''
  :instructions: 'Not mapped'
:site_id:
  :MIMSY: SITES.SITE_ID
  :module: 'esites'
  :column: 'SitSiteNumber'
  :instructions: ''
:site_type:
  :MIMSY: SITES.SITE_TYPE
  :module: 'esites'
  :column: 'LocSiteType'
  :instructions: ''
:site_name:
  :MIMSY: SITES.SITE_NAME
  :module: 'esites'
  :column: 'SitSiteName_tab'
  :instructions: ''
:environment:
  :MIMSY: SITES.SITE_CLASS
  :module: 'esites'
  :column: 'LocEnvironment'
  :instructions: ''
:description:
  :MIMSY: SITES.DESCRIPTION
  :module: 'esites'
  :column: 'LocPreciseLocation'
  :instructions: ''
:site_date:
  :MIMSY: SITES.SITE_DATE
  :module: 'ecollectionevents'
  :column: 'ColVerbatimDate'
  :instructions: 'Retrieve collection event through link to Catalog via CatalogSite; where possible, parse content into ecollectionevents:ColDateVisitedFrom, ecollectionevents:ColDateVisitedTo, ecollectionevents:ColTimeVisitedFrom, and ecollectionevents:ColTimeVisitedTo'
:location:
  :MIMSY: SITES.LOCATION
  :module: ''
  :column: ''
  :instructions: 'Not mapped'
:location_accuracy:
  :MIMSY: SITES.LOCATION_ACCURACY
  :module: 'esites'
  :column: 'LatGeoreferencingNotes0'
  :instructions: ''
:start_latitude:
  :MIMSY: SITES.START_LATITUDE
  :module: 'esites'
  :column: 'LatLatitude_nesttab'
  :instructions: ''
:start_longitude:
  :MIMSY: SITES.START_LONGITUDE
  :module: 'esites'
  :column: 'LatLongitude_nesttab'
  :instructions: 'Make LatCentroidType_tab = "Start" for start coordinate'
:end_latitude:
  :MIMSY: SITES.END_LATITUDE
  :module: 'esites'
  :column: 'LatLatitude_nesttab'
  :instructions: ''
:end_longitude:
  :MIMSY: SITES.END_LONGITUDE
  :module: 'esites'
  :column: 'LatLongitude_nesttab'
  :instructions: 'Make LatCentroidType_tab = "End" for end coordinate'
:utm_start:
  :MIMSY: SITES.UTM_START
  :module: 'esites'
  :column: 'MapUTMVerbatim_tab'
  :instructions: 'Parse the values here into MapZone_tab, MapEasting0, and MapNorthing0. Put "Start" in MapUTMComment_tab. Most values will be in the form "Zone 16; Northing 5610010; Easting 678499"'
:utm_end:
  :MIMSY: SITES.UTM_END
  :module: 'esites'
  :column: 'MapUTMVerbatim_tab'
  :instructions: 'Parse the values here into MapZone_tab, MapEasting0, and MapNorthing0. Put "End" in MapUTMComment_tab. Most values will be in the form "Zone 16; Northing 5610010; Easting 678499"'
:start_latitude_dec:
  :MIMSY: SITES.START_LATITUDE_DEC
  :module: 'esites'
  :column: 'LatLatitudeDecimal_nesttab'
  :instructions: ''
:start_longitude_dec:
  :MIMSY: SITES.START_LONGITUDE_DEC
  :module: 'esites'
  :column: 'LatLongitudeDecimal_nesttab'
  :instructions: ''
:end_latitude_dec:
  :MIMSY: SITES.END_LATITUDE_DEC
  :module: 'esites'
  :column: 'LatLatitudeDecimal_nesttab'
  :instructions: ''
:end_longitude_dec:
  :MIMSY: SITES.END_LONGITUDE_DEC
  :module: 'esites'
  :column: 'LatLongitudeDecimal_nesttab'
  :instructions: ''
:decimal_is_primary:
  :MIMSY: SITES.DECIMAL_IS_PRIMARY
  :module: 'esites'
  :column: 'LatComment_nesttab'
  :instructions: 'If true, set = "Decimal is primary"'
:coord_uncertainty:
  :MIMSY: SITES.COORD_UNCERTAINTY
  :module: 'esites'
  :column: 'LatRadiusNumeric_tab'
  :instructions: ''
:coord_uncertainty_verb:
  :MIMSY: SITES.COORD_UNCERTAINTY_VERB
  :module: 'esites'
  :column: 'LatRadiusVerbatim_tab'
  :instructions: ''
:uncertainty_unit:
  :MIMSY: SITES.UNCERTAINTY_UNIT
  :module: 'esites'
  :column: 'LatRadiusUnit_tab'
  :instructions: ''
:georef_status:
  :MIMSY: SITES.GEOREF_STATUS
  :module: 'esites'
  :column: '???'
  :instructions: 'Georef. Status field in client has Column = LatRadiusProbability_tab and Type = Float. Needs fix in client.'
:georef_source:
  :MIMSY: SITES.GEOREF_SOURCE
  :module: 'esites'
  :column: 'LatDetSource_tab'
  :instructions: ''
:geodetic_datum:
  :MIMSY: SITES.GEODETIC_DATUM
  :module: 'esites'
  :column: 'LatDatum_tab'
  :instructions: ''
:measurements:
  :MIMSY: SITES.MEASUREMENTS
  :module: ''
  :column: ''
  :instructions: 'See associated SiteMeasurement records through Site.id = SiteMeasurement.site_id'
:elevation:
  :MIMSY: SITES.ELEVATION
  :module: 'esites'
  :column: 'LocElevationASLFromMt'
  :instructions: 'Values here may include all manner of values, ranges, and units. Please parse and convert these values into meters when required and also populate LocElevationASLToMt as appropriate when ranges are indicated.'
:topography:
  :MIMSY: SITES.TOPOGRAPHY
  :module: 'esites'
  :column: 'TerTopography'
  :instructions: ''
:ecological_zones:
  :MIMSY: SITES.ECOLOGICAL_ZONES
  :module: 'esites'
  :column: 'HabHabitatRemarks'
  :instructions: ''
:vegetation:
  :MIMSY: SITES.VEGETATION
  :module: 'esites'
  :column: 'TerVegetation'
  :instructions: ''
:disturbance_factors:
  :MIMSY: SITES.DISTURBANCE_FACTORS
  :module: 'esites'
  :column: 'CulDisturbance'
  :instructions: ''
:condition:
  :MIMSY: SITES.CONDITION
  :module: 'esites'
  :column: 'CulCondition'
  :instructions: ''
:owner:
  :MIMSY: SITES.OWNER
  :module: 'esites'
  :column: 'SitSiteOwner_tab'
  :instructions: ''
:register_status:
  :MIMSY: SITES.REGISTER_STATUS
  :module: 'ecollectionevents'
  :column: 'ExpVesselName'
  :instructions: 'Retrieve collection event through link to Catalog via CatalogSite'
:archaeological_status:
  :MIMSY: SITES.ARCHAEOLOGICAL_STATUS
  :module: 'ecollectionevents'
  :column: 'ExpExpeditionName'
  :instructions: 'Retrieve collection event through link to Catalog via CatalogSite; also put content in esites:CulExpeditionName_tab'
:jurisdiction:
  :MIMSY: SITES.JURISDICTION
  :module: 'esites'
  :column: 'SitJursidiction'
  :instructions: ''
:site_designation:
  :MIMSY: SITES.SITE_DESIGNATION
  :module: 'esites'
  :column: 'CulResearchCategory_tab'
  :instructions: ''
:research_activity:
  :MIMSY: SITES.RESEARCH_ACTIVITY
  :module: 'esites'
  :column: 'CulResearchActivity_tab'
  :instructions: ''
:recommendations:
  :MIMSY: SITES.RECOMMENDATIONS
  :module: 'esites'
  :column: 'LocNotes'
  :instructions: ''
:note:
  :MIMSY: SITES.NOTE
  :module: 'esites'
  :column: 'NotNotes'
  :instructions: 'Append to field'
:publish:
  :MIMSY: SITES.PUBLISH
  :module: 'esites'
  :column: 'AdmPublishWebNoPassword'
  :instructions: 'If value is false or null, mark both Publish on Internet and Intranet as No; if value is true, mark both as Yes.'
:option1:
  :MIMSY: SITES.OPTION1
  :module: 'esites'
  :column: 'NotNotes'
  :instructions: 'Append to field'
:option2:
  :MIMSY: SITES.OPTION2
  :module: 'esites'
  :column: 'NotNotes'
  :instructions: 'Append to field'
:flag1:
  :MIMSY: SITES.FLAG1
  :module: ''
  :column: ''
  :instructions: 'Not mapped'
:flag2:
  :MIMSY: SITES.FLAG2
  :module: ''
  :column: ''
  :instructions: 'Not mapped'
:sort_prefix:
  :MIMSY: SITES.SORT_PREFIX
  :module: ''
  :column: ''
  :instructions: 'Not mapped'
:sort1:
  :MIMSY: SITES.SORT1
  :module: ''
  :column: ''
  :instructions: 'Not mapped'
:sort2:
  :MIMSY: SITES.SORT2
  :module: ''
  :column: ''
  :instructions: 'Not mapped'
:sort3:
  :MIMSY: SITES.SORT3
  :module: ''
  :column: ''
  :instructions: 'Not mapped'
:sort4:
  :MIMSY: SITES.SORT4
  :module: ''
  :column: ''
  :instructions: 'Not mapped'
:sort5:
  :MIMSY: SITES.SORT5
  :module: ''
  :column: ''
  :instructions: 'Not mapped'
:create_date:
  :MIMSY: SITES.CREATE_DATE
  :module: ''
  :column: ''
  :instructions: 'Not mapped'
:created_by:
  :MIMSY: SITES.CREATED_BY
  :module: ''
  :column: ''
  :instructions: 'Not mapped'
:update_date:
  :MIMSY: SITES.UPDATE_DATE
  :module: ''
  :column: ''
  :instructions: 'Not mapped'
:updated_by:
  :MIMSY: SITES.UPDATED_BY
  :module: ''
  :column: ''
  :instructions: 'Not mapped'
